### ISSUE TITLE
1st: welcome

### ISSUE THREAD

**Issue by ionescu77** [munteanuabriel25/Django-explore-city#1]
Salutare,

Primul lucru pt tine sau altcineva este un readme.md

Vezi că îți sugerează și github readme în format markdown.

## to-do's

- [ ] Create readme.md
- [ ] Write environment data eg.: tested on windows 10, python 3.8, django 3.x
- [ ] Any special recomandat-o s for building and starting the project

**Comment by ionescu77** [comment]
## Exemplu

Repo-ul meu cu site-ul firmei. Este public, dar nu am salvat parole, sau altele și este okay.

Te rog să nu "furi" poza de background :)

Aruncă o privire, vezi cum este structurat, dacă înțelegi cum funcționează.

Dacă ai întrebări poți scrie aici la tine, sau faci un issue.

https://github.com/ionescu77/avproiect.com
